# Generated by Django 5.2.6 on 2026-09-08 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('stats', models.JSONField(default=dict)),
                ('unattributable', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'reconciliation_ingestrun',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_ref', models.CharField(db_index=True, max_length=64)),
                ('code', models.CharField(db_index=True, max_length=64)),
                ('summary', models.TextField()),
                ('entry_ids', models.JSONField(default=list)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_notes', to='tenancy.org')),
            ],
            options={
                'db_table': 'reconciliation_matchnote',
                'ordering': ['record_ref', 'code'],
            },
        ),
        migrations.CreateModel(
            name='SourceEntryB',
            fields=[
                ('entry_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('raw_record_ref', models.CharField(max_length=64)),
                ('record_ref', models.CharField(blank=True, db_index=True, max_length=64)),
                ('location_id', models.CharField(max_length=32)),
                ('recorded_on', models.DateField(null=True)),
                ('raw_value', models.CharField(blank=True, max_length=64)),
                ('value', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('reference_was_normalised', models.BooleanField(default=False)),
                ('amount_format_was_normalised', models.BooleanField(default=False)),
                ('source_row_number', models.IntegerField()),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='tenancy.org')),
            ],
            options={
                'db_table': 'reconciliation_sourceentryb',
                'ordering': ['entry_id'],
            },
        ),
        migrations.CreateModel(
            name='SourceRecordA',
            fields=[
                ('record_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('location_id', models.CharField(max_length=32)),
                ('event_date', models.DateField(null=True)),
                ('category_code', models.CharField(max_length=32)),
                ('actor_id', models.CharField(blank=True, max_length=32)),
                ('base_value', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('adjustment', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('state', models.CharField(max_length=32)),
                ('source_row_number', models.IntegerField()),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='tenancy.org')),
            ],
            options={
                'db_table': 'reconciliation_sourcerecorda',
                'ordering': ['record_id'],
            },
        ),
        migrations.CreateModel(
            name='Exception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_ref', models.CharField(db_index=True, max_length=64)),
                ('reason_code', models.CharField(choices=[('MISSING_IN_SYSTEM_B', 'Missing from System B'), ('UNKNOWN_RECORD_IN_SYSTEM_B', 'System B entry for an unknown record'), ('UNREADABLE_REFERENCE_IN_SYSTEM_B', 'System B reference cannot be read'), ('DUPLICATE_ENTRY_IN_SYSTEM_B', 'Recorded more than once in System B'), ('AMOUNT_MISMATCH', 'Amounts disagree'), ('ADJUSTMENT_MISSING_IN_SYSTEM_B', 'System B is missing the adjustment'), ('AMOUNT_MISSING_IN_SYSTEM_B', 'System B has no amount'), ('SPLIT_ENTRIES_DO_NOT_ADD_UP', 'Split entries do not add up'), ('EVENT_DATE_MISMATCH', 'Dates disagree'), ('LOCATION_MISMATCH', 'Locations disagree'), ('VOIDED_RECORD_STILL_IN_SYSTEM_B', 'Voided record still live in System B')], db_index=True, max_length=64)),
                ('summary', models.TextField()),
                ('location_id', models.CharField(blank=True, db_index=True, max_length=32)),
                ('location_name', models.CharField(blank=True, max_length=120)),
                ('event_date', models.DateField(null=True)),
                ('category_code', models.CharField(blank=True, max_length=32)),
                ('system_a_amount', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('system_b_amount', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('difference', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('entry_ids', models.JSONField(default=list)),
                ('detail', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='tenancy.org')),
            ],
            options={
                'db_table': 'reconciliation_exception',
                'ordering': ['record_ref', 'reason_code'],
                'constraints': [models.UniqueConstraint(fields=('org', 'record_ref', 'reason_code'), name='unique_exception_per_record_and_reason')],
            },
        ),
    ]
